### ISSUE TITLE
Query about an old repo

### ISSUE THREAD

**Issue by ash-williams** [maina401/ConsoleApp1#1]
Hi Moffat,

This isn't an issue on this repo - I just wasn't sure how else to contact you.

I'm a software engineering lecturer in the UK. We believe that one of our students may have submitted one of your repo's as their own work. However, the repo is no longer visible on your GitHub. We were wondering if you'd mind providing access so that we can investigate further. The repo was a dental booking system: turbo-parakeet.git

Cheers,
Ash

**Comment by maina401** [comment]
Hi Williams. Sorry for what you are experiencing. 
I wish to confirm that the repo existed in my repos.
However, I am and was not the owner of that specific repo. I was just helping out fixing some issues for a "friend". (In quotes because is a friend from a coder community.
So yeah, the friend might have been your student.
